### ISSUE TITLE
Feature request: add reverse functionality

### ISSUE THREAD

**Issue by dbkaplun** [kellym/smartquotesjs#15]
My use case is that I need to convert text to replace smart quotes with dumb quotes to feed to an NLP processor that errors on smart quotes. It would be great if the smart quote characters were exported as well, or a function like `smartquotes.dumb()` would also be good.

**Comment by jonahgreenthal** [comment]
Isn't this a much simpler problem to solve? I would have thought it can be handled by a pure textual replacement of `“` and `”` to `"`, and `‘` and `’` to `'`.

**Comment by kellym** [comment]
Agreed. A simple regex or string replace could easily reverse smart quotes. I wouldn't bother with including a dependency just to do that.

**Comment by NousSachons** [comment]
Hello! I would like to reopen this issue because I would need this feature to improve my tests with codeceptJS. Let me explain the issue I'm facing:

I'm testing a mobile app. I use Appium and the codeceptJS framework to implement the tests. CodeceptJS is a "helper" framework that has to simplify the access to the appium features. 

I have to test the labels of the app by comparing the text value extracted from an element with a label of reference stored in a json file. I extracted this JSON file from the tool "phrase", that is used to implement the translations of the app, and I would like to automate the update of JSON files with Phrase's API.

The instruction to check label is :
**await I.see(wording.textToCheck, ~element_Id);**

**~element_Id** is the locator of the element
**wording.textToCheck** is the value of the key "textToCheck" inside the JSON file imported into the wording variable. This value is displayed like that inside the json file :
**"textToCheck": "blabla “Agree” blabla “Disagree”."**

That means my instruction is actually:
**await I.see("blabla “Agree” blabla “Disagree”.", ~element_Id);**

The test failed because the text inside ~element_Id is actually : **blabla "Agree" blabla "Disagree".**

I can't write **await I.see("blabla “Agree” blabla “Disagree”.", smartquotes(~element_Id));** because ~element_Id is not a string. I also would rather not to implement a new layer on the codeceptJS framework. The ideal solution for this case would by to convert smart quotes into dumb quotes, and then write:
**await I.see(smartquotes.dumb(wording.textToCheck), ~element_Id);**

Sorry for this long explanation. Do you know any workaround (except implementing a new feature on the framework side or on appium) ?

Thank you very much for reading me ;-)

.
