### ISSUE TITLE
npm support & gulp plugin

### ISSUE THREAD

**Issue by callumacrae** [kellym/smartquotesjs#7]
Hey!

This issue builds on #6 slightly. I would like the ability to use this library on the server-side as well as on the client—I want to write a gulp plugin to run this library on HTML. Currently the way this library is structured, that is impossible.

It would be possible to restructure this library so that it works on both the client, but it would be a breaking change.

On the client:

```html
<script src="smartquotes.js></script>
<script> smartquotes() </script>
```

This approach would add the possibility to pass in options, such as saying they only want smart quotes and not em dashes, or restricting it to certain selectors.

On the server:

```js
var smartquotes = require('smartquotesjs');

var newHtml = smartquotes(oldHtml);
```

This could be done with as little inconvenience to your existing users as possible, while making it possible to use server-side, and create a gulp plugin.

If you'd be interested in this, I'd be willing to do it.

**Comment by callumacrae** [comment]
@kellym: Are you still maintaining this project?

**Comment by kellym** [comment]
Hey @callumacrae, sorry for the delays.  There's been a few things lately holding me back from contributing to the conversations. I'm still maintaining it, and I like where you're headed.

I think it'd be a great idea for this to support using Gulp. I hesitated for a bit because I know there are so many frameworks out there with different syntaxes, but I think updating this to work server-side makes sense long-term.

:+1:

**Comment by callumacrae** [comment]
Cool. I'll do some stuff and send a pull request soon :smiley:
